### ISSUE TITLE
Error: Julia: type OpSum has no field second_q_ops

### ISSUE THREAD

**Issue by saharbenrached** [Qiskit-Extensions/qiskit-alt#32]
Computing the ground state energy with [GroundStateEigensolver().solve()](https://qiskit.org/documentation/nature/stubs/qiskit_nature.algorithms.GroundStateEigensolver.html#qiskit_nature.algorithms.GroundStateEigensolver) from Qiskit raises the following error: `Julia: type OpSum has no field second_q_ops`.

**Comment by jlapeyre** [comment]
I think we determined this is not a bug.
